#Главный конфиг сервера

dataBase:
  type: "SQLite" #Счас только SQLite, позже будут другие (наверно)
  fileRelativePath: "database"
  userName: "none"
  userPassword: "none"

tpr:
  delay: 10 #Время в секундах между телепортациями
  maxX: 10000 #Максимальная точка по x
  maxZ: 10000 #Максимальная точка по z
  minX: -10000 #Минимальная точка по x
  minZ: -10000 #Минимальная точка по z

chat:
  localChatRadius: 100 #На каком расстоянии действует локальный чат

helpop:
  timeForMark: 3600 #Время, после которого нельзя будет поставить отметку

tpa:
  expire: 120 #Через какое время истекает запрос (в секундах)

home:
  maxLength: 100 #Максимальная длинна названия

warp:
  maxLength: 100 #Максимальная длинна названия

kit:
  start: "start" #Набор, который выдается при первом заходе